blank_issues_enabled: true
contact_links:
  - name: creator
    url: https://creator.blockysite.com/
    about: Develop webistes without coding.
  - name: Instagram
    url: https://www.instagram.com/blockysite/
    about: Follow us on instagram for more updates.
